namespace Clutch.Core.Requests
{
    using System;

    /// <summary>
    /// Request to create an application key (credential). The access and secret keys are generated by
    /// the server; the raw secret is returned only once in the response.
    /// </summary>
    public class CreateCredentialRequest
    {
        #region Public-Members

        /// <summary>
        /// Human-readable name.
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Owning user identifier, if any.
        /// </summary>
        public string? UserId { get; set; } = null;

        /// <summary>
        /// Optional expiration timestamp.
        /// </summary>
        public DateTime? ExpiresUtc { get; set; } = null;

        #endregion
    }
}
