global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: clutch-nodes
    metrics_path: /metrics
    static_configs:
      - targets:
          - clutch-node1:9464
          - clutch-node2:9464
