<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Version>0.3.0</Version>
    <StartupObject>Clutch.Server.Program</StartupObject>
    <NoWarn>1701;1702</NoWarn>
    <IsAotCompatible>true</IsAotCompatible>
    <WarningsAsErrors>$(WarningsAsErrors);IL2026;IL2046;IL2057;IL2067;IL2070;IL2072;IL2075;IL2087;IL2090;IL2091;IL3050;IL3051</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Voltaic" Version="2.3.0" />
    <PackageReference Include="Watson" Version="7.3.0" />
    <PackageReference Include="SyslogLogging" Version="2.3.1" />
    <PackageReference Include="Radiant" Version="0.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Clutch.Core\Clutch.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Test.Shared" />
  </ItemGroup>

  <ItemGroup>
    <None Update="clutch.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
